### ISSUE TITLE
Problem in cloning a desc-python-bleed environnement at NERSC

### ISSUE THREAD

**Issue by sylvielsstfr** [LSSTDESC/desc-python#151]
I want to reinstall myself all the rail packages in a desc-python-bleed environnement to debug why delight algo is not installed.
I hope I can ask this kind of question here.

I follow step by step the instruction I got from last sprint-days.
In particular I follow this doc : https://github.com/LSSTDESC/desc-python/wiki/Add-Packages-to-the-desc-python-environment

In fact I want to install for me all my python installations here /global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024.

 In particular I tried to install those environnement below mydesc2024/
mydescpython  
mydescpythonbleed  
mydescstack

In the past I was succesfull with mydescpython , but today I want  mydescpythonbleed .  

You can see that my .bashrc define the environnement variable required:
(desc-py)dagoret@perlmutter:login15:~> more .bashrc
export DESCUSERENV=/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython
export DESCPYTHONBLEEDUSERAREA=/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpythonbleed
export DESCSTACKUSERBASE=/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescstack

But when I do :
python /global/common/software/lsst/common/miniconda/start-kernel-cli.py desc-python-bleed

I get a missing package shifter

Starting an environment for desc-python-bleed now...
This may take a while. Be patient...
Traceback (most recent call last):
  File "/global/common/software/lsst/common/miniconda/start-kernel-cli.py", line 62, in <module>
    subprocess.call(command)
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'shifter'
(desc-py)dagoret@login15:/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpythonbleed$ cd ..
(desc-py)dagoret@login15:/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024$ ls
mydescpython  mydescpythonbleed  mydescstack
(desc-py)dagoret@login15:/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024$ python /global/common/software/lsst/common/miniconda/start-kernel-cli.py desc-python-bleed
Starting an environment for desc-python-bleed now...
This may take a while. Be patient...
Traceback (most recent call last):
  File "/global/common/software/lsst/common/miniconda/start-kernel-cli.py", line 62, in <module>
    subprocess.call(command)
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/global/cfs/cdirs/lsst/groups/PC/users/dagoret/mydesc2024/mydescpython/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'shifter'

Why shifter is missing ?

**Comment by heather999** [comment]
HI @sylvielsstfr sorry for the delay.  I was hoping to just add LSSTDESC/Delight directly to desc-python-bleed to help avoid having you install it yourself. So far, while I can do the installation for Delight, the tests fail -I can't verify that LSSTDESC/Delight works currently - but I guess others in RAIL are using it, so perhaps I have nothing to worry about.  See the continuing thread [here](https://lsstc.slack.com/archives/CQGKM0WKD/p1727231395593179?thread_ts=1726844928.008419&cid=CQGKM0WKD).

So for now.. let's see if I can help you install it yourself using desc-python-bleed:

I would follow the first way to install your own packages described here: https://github.com/LSSTDESC/desc-python/wiki/Add-Packages-to-the-desc-python-environment#first-way-to-install-additional-packages-for-use-with-desc-python
as you noted desc-python-bleed is a shifter (container) - using the above instructions should work both with containers and with environments natively installed at NERSC.
Here are the specific steps:
```
cd $SCRATCH   # I just chose SCRATCH.. you could use another area
mkdir <yourInstallArea>
export DESCPYTHONBLEEDUSERBASE=$PWD/<yourInstallArea> 
python /global/common/software/lsst/common/miniconda/start-kernel-cli.py desc-python-bleed
```
Now we have to follow the Delight installation instructions with a minor adjustment.  I'm looking at the install instructions linked from the LSSTDESC/Delight README: https://delight.readthedocs.io/en/latest/install.html#id1
First I git clone the repo:
```
https://github.com/LSSTDESC/Delight.git
cd Delight
python -m pip cache purge  # I also like to purge my local cache just to make sure I'm doing a fresh installation of all packages
pip install --user --no-build-isolation -r requirements.txt
python setup.py build_ext --inplace
python install --user --no-build-isolation . 
```
That seems to work and i can see `delight` in my package list when I do:  `conda list`
and I can successfully do `import delight` in Python.  
I can't run the tests for Delight as I noted on the Slack thread I linked above, so I am reluctant to include LSSTDESC/Delight in the desc-python-bleed environment unless someone can explain that these test failures are expected or how to fix it.  But.. I think this is ok for you to try for your own use.

After you do that initial installation of Delight, you just need to make sure to set your DESCPYTHONBLEEDUSERBASE environment variable in every NERSC session and/or you could consider adding `export DESCPYTHONBLEEDUSERBASE=<your installation area>` in your $HOME/.bashrc, so that it is always set up to use your local install of Delight. Updating your $HOME/.bashrc also meant that when you use Jupyter, the desc-python-bleed environment will include your installation of Delight. 

Just let me know if you have trouble.. or if you can help determine that LSSTDESC/Delight is installed correctly!

**Comment by sylvielsstfr** [comment]
Many thanks Heather,

I could get the desc-python-bleed environnement using all your recommendations about the purge. 

I just had to replace : 

python install --user --no-build-isolation . 
by
pip install --user --no-build-isolation .

 But now I really have to tackle Delight which is not woking. I will go with Sam to dive deeper in the code.

**Comment by heather999** [comment]
Thank you Sylvie!  
Once Delight is working again, just let me know and we can get it into desc-python!

**Comment by sylvielsstfr** [comment]
Hi Heather, Yes OK it is hard to find time for work. It is on my heap.
